name: Build and Publish to JSR

on:
    push:
        tags:
            - ['v*.*.*'] # e.g. v1.2.3

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            # Extract version from git tag (removes the "v" prefix)
            - name: Extract version from tag
              id: vars
              run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

            # Update deno.json with version from git tag
            - name: Update deno.json version
              run: |
                  version="${{ steps.vars.outputs.version }}"
                  jq --arg v "$version" '.version = $v' deno.json > deno.json.tmp
                  mv deno.json.tmp deno.json

            - name: Run tests
              run: deno test -A

            - name: Publish to JSR
              run: deno publish --dry-run
